name: Static code analysis

on: pull_request

jobs:
    static-code-analysis:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3
              with:
                submodules: recursive
            - name: Set up php
              uses: shivammathur/setup-php@master
              with:
                php-version: 8.0
                extensions: ctype,curl,dom,fileinfo,gd,intl,json,mbstring,openssl,pdo_sqlite,posix,sqlite,xml,zip
                coverage: none
            - name: Composer install
              run: composer i
            - name: Psalm
              run: composer run psalm -- --monochrome --no-progress --output-format=github --update-baseline --report=results.sarif || ( git diff -- . ':!lib/composer' && exit 1 )
            - name: Show potential changes in Psalm baseline
              run: git diff -- . ':!lib/composer'
            - name: Upload Analysis results to GitHub
              uses: github/codeql-action/upload-sarif@v2
              with:
                sarif_file: results.sarif

    static-code-analysis-security:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3
              with:
                submodules: recursive
            - name: Set up php
              uses: shivammathur/setup-php@master
              with:
                php-version: 8.0
                extensions: ctype,curl,dom,fileinfo,gd,intl,json,mbstring,openssl,pdo_sqlite,posix,sqlite,xml,zip
                coverage: none
            - name: Composer install
              run: composer i
            - name: Psalm taint analysis
              run: composer run psalm -- --monochrome --no-progress --output-format=github --update-baseline --report=results.sarif --taint-analysis || ( git diff -- . ':!lib/composer' && exit 1 )
            - name: Upload Security Analysis results to GitHub
              uses: github/codeql-action/upload-sarif@v2
              with:
                sarif_file: results.sarif

    static-code-analysis-ocp:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3
              with:
                submodules: recursive
            - name: Set up php
              uses: shivammathur/setup-php@master
              with:
                php-version: 8.0
                extensions: ctype,curl,dom,fileinfo,gd,intl,json,mbstring,openssl,pdo_sqlite,posix,sqlite,xml,zip
                coverage: none
            - name: Composer install
              run: composer i
            - name: Psalm
              run: composer run psalm -- -c psalm-ocp.xml --monochrome --no-progress --output-format=github --update-baseline || ( git diff -- . ':!lib/composer' && exit 1 )
            - name: Show potential changes in Psalm baseline
              run: git diff -- . ':!lib/composer'
